packages:
  - node@22

build:
  commands:
    - npm install -g pnpm
    - pnpm install --frozen-lockfile
    - pnpm run build
  workdir: ./backend

start:
  command: pnpm run start
  workdir: ./backend