build:
  packages:
    - node@22
  workdir: ./backend
  install:
    - npm install -g pnpm
    - pnpm install --frozen-lockfile
  build: pnpm run build

start:
  workdir: ./backend
  command: pnpm run start